baseURL: http://www.example.com
title: Saajan
theme: hugo-coder
languageCode: en
defaultContentLanguage: en
paginate: 20
pygmentsStyle: b2
pygmentsCodeFences: yes
pygmentsCodeFencesGuessSyntax: yes
disqusShortname: yourdiscussshortname
params:
  author: Saajan
  avatarURL: images/golden_ratio.jpg
  cloudflare:
    token: token
  colorScheme: auto
  commit: https://github.com/luizdepra/hugo-coder/tree/
  customCSS: []
  customJS: []
  customSCSS: []
  dateFormat: January 2, 2006
  description: Saajan personal website
  enableTwemoji: yes
  fathomAnalytics:
    serverURL: analytics.example.com
    siteID: ABCDE
  footerContent: Enter a text here.
  goatCounter:
    code: code
  hideColorSchemeToggle: no
  hideCopyright: yes
  hideCredits: yes
  hideFooter: yes
  info: Data Imagainist
  keywords: blog,developer,personal,saajanrajak
  maxSeeAlsoItems: 5
  plausibleAnalytics:
    domain: example.com
    serverURL: analytics.example.com
  rtl: no
  since: 2019
  social:
    - icon: fa fa-github
      name: Github
      url: https://github.com/saajanrajak/
      weight: 1
    - icon: fa fa-twitter
      name: Twitter
      url: https://twitter.com/saajanrajak/
      weight: 2
    - icon: fa fa-linkedin
      name: LinkedIn
      url: https://www.linkedin.com/in/saajanrajak/
      weight: 3
taxonomies:
  author: authors
  category: categories
  series: series
  tag: tags
languages:
  en:
    languageName: English
    menu:
      main:
        - name: About
          url: about/
          weight: 1
        - name: Blog
          url: posts/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Contact me
          url: contact/
          weight: 4
          
 
