---
title: "Logistic Regression Basics"
author: "Saajan"
date: 2021-08-15
output: html_document
categories: ["Statistics","Machine Learning" ]
tags: ["Machine Learning", "Regression", "Algebra", "Logistic"]
math: TRUE
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
data_url <- "https://raw.githubusercontent.com/saajanrajak/data/main/train_house_price.csv"
raw_data <- read_csv(data_url)
```



# **Introduction**

The Objective of this blog is to understand basic concepts of Logistic Regressio. We are going to learn today

- **What is Logistic Regression?**
- **Logistic Regression Programming in R**
- **Interpreting Logistic Regression Results**

# **What is Logistic Regression**

Logistic Regression is predictive modeling technique for **discrete/categorical outcome** from single/set of input variables. The most common logistic regression outcomes are **Yes/No**, **TRUE/False**, **1/0**, **Small/Medium/Large**.
 is a part of Supervised Learning. 
 
- **Binary Logistic Regression**: Logistic Regression where output variable is 2 types. Like **This/That**, **Yes/No**, **A/B**
- **Multinomial Logistic Regression**: Logistic Regression where output variable is more than 2 types. Example **A/B/C**, **Small/Medium/Large**. 


Logistic Regression is one of the most commonly used predictive technique to predict binary classification problem.

Real world Examples.

- E-commerce company want to know which customer would like to be **Retained/Churn** from new customers that are coming to their site, by  customer behavior data. To Increase the ROI, they would like to give promotional offers to customers who is more likely to be retained.
- Similarly, Credit Company wants to predict which customer is going to be **Defaulter/Not Defaulter** on credit card by characteristics like Customer Annual Income, Monthly credit card payment,  number of defaults etc.



## **Logistic v/s Linear Regression
 
The main difference between Logistic and Linear regression is type of output variable. Linear Regression output variable is **Continous** while Logistic Regression output variable is **Discrete/Categorical**.

Examples
- Linear Regression: How many products a customer can buy in a month period.
- Logistic Regression: Would this customer will buy again after a month from his first order date.





# **Logistic Regression Programming in R**

# **Interpreting Logistic Regression Results**
